# Generated by Django 4.1.3 on 2023-08-05 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('favorite', models.BooleanField(blank=True, null=True)),
                ('image_url', models.CharField(default=1, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Cup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('difficulty', models.CharField(max_length=50)),
                ('theme', models.CharField(max_length=50)),
                ('image_url', models.CharField(default=1, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image_url', models.CharField(default=1, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default=1, max_length=50)),
                ('character_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kariomartapi.character')),
                ('map_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kariomartapi.map')),
                ('vehicle_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kariomartapi.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='CupRace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cup_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kariomartapi.cup')),
                ('cup_race_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kariomartapi.race')),
            ],
        ),
        migrations.AddField(
            model_name='cup',
            name='race_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kariomartapi.race'),
        ),
    ]
