# Generated by Django 4.1.3 on 2023-08-09 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kariomartapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cup',
            name='image_url',
            field=models.CharField(default=1, max_length=1000),
        ),
    ]
