# Generated by Django 4.2.1 on 2023-08-05 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kariomartapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='race',
            name='character_vehicle_id',
        ),
        migrations.AddField(
            model_name='race',
            name='character_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kariomartapi.character'),
        ),
        migrations.AddField(
            model_name='race',
            name='uid',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AddField(
            model_name='race',
            name='vehicle_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kariomartapi.vehicle'),
        ),
        migrations.CreateModel(
            name='CupRace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cup_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kariomartapi.cup')),
                ('race_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kariomartapi.race')),
            ],
        ),
        migrations.AddField(
            model_name='cup',
            name='race_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kariomartapi.race'),
        ),
    ]
