# Generated by Django 4.2.1 on 2023-08-01 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kariomartapi', '0002_character_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='image_url',
            field=models.CharField(default=1, max_length=1000),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='image_url',
            field=models.CharField(default=1, max_length=1000),
        ),
    ]
